---

atom_package_url: "https://atom.io/download/deb"

atom_packages:
  - atom-beautify
  - atom-jinja2
  - atom-material-syntax
  - atom-material-syntax-dark
  - atom-material-syntax-light
  - atom-material-ui
  - atom-runner
  - autocomplete-python
  #- autocomplete-ruby
  - auto-detect-indentation
  - busy-signal
  - emmet
  - file-icons
  - fonts
  - git-blame
  - git-plus
  - git-projects
  #- hiera-eyaml
  - highlight-selected
  - intentions
  - language-ini
  #- language-puppet
  - linter
  - linter-erb
  - linter-jsonlint
  - linter-js-yaml
  #- linter-puppet-lint
  - linter-pylint
  - linter-rubocop
  - linter-shellcheck
  - linter-ui-default
  - merge-conflicts
  - minimap
  - platformio-ide-terminal
  - project-manager
  - script
  - todo-show
  - vim-mode-plus
  - vim-mode-plus-ex-mode

...
