---

vscode_package_url: "https://vscode-update.azurewebsites.net/latest/linux-deb-x64/stable"

vscode_extensions:
  - donjayamanne.githistory
  - eamodio.gitlens
  - Equinusocio.vsc-material-theme
  - formulahendry.code-runner
  - ms-python.python
  - ms-vscode.Go
  - PKief.material-icon-theme
  - vscodevim.vim
  - vscoss.vscode-ansible
  - yzhang.markdown-all-in-one

...
