---

- name: install dependency package for atom editor
  apt:
    name: gconf2
    state: present

# download atom deb file first and them attmept to install
# direct install using apt fails often
- block:
    - name: download atom deb file
      get_url:
        url: "{{ atom_package_url  }}"
        dest: /tmp/atom.deb

    - name: install atom editor
      apt:
        deb: /tmp/atom.deb

- name: install atom editor packages
  command: apm install {{ item }}
  with_items: "{{ atom_packages }}"
  become: yes
  become_user: "{{ local_username }}"
