---

- name: install vim apt packages
  apt:
    name: "{{ vim_apt_packages }}"
    state: latest

- block:
    - name: install Janus Vim Distribution
      shell: "curl -sLf {{ vim_janusvim_url }} | bash"

  become: yes
  become_user: "{{ local_username }}"

...
